# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'View/tela_execucao.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TelaExecucao(object):
    def setupUi(self, TelaExecucao):
        TelaExecucao.setObjectName("TelaExecucao")
        TelaExecucao.resize(1024, 768)
        self.lbNumPecasAprovadas = QtWidgets.QLabel(TelaExecucao)
        self.lbNumPecasAprovadas.setGeometry(QtCore.QRect(70, 150, 361, 91))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.lbNumPecasAprovadas.setFont(font)
        self.lbNumPecasAprovadas.setStyleSheet("background-color: rgb(171, 171, 171);")
        self.lbNumPecasAprovadas.setObjectName("lbNumPecasAprovadas")
        self.label_2 = QtWidgets.QLabel(TelaExecucao)
        self.label_2.setGeometry(QtCore.QRect(60, 80, 381, 61))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(TelaExecucao)
        self.label_3.setGeometry(QtCore.QRect(580, 80, 381, 61))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lbNumPecasReprovadas = QtWidgets.QLabel(TelaExecucao)
        self.lbNumPecasReprovadas.setGeometry(QtCore.QRect(590, 150, 361, 91))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.lbNumPecasReprovadas.setFont(font)
        self.lbNumPecasReprovadas.setStyleSheet("background-color: rgb(171, 171, 171);")
        self.lbNumPecasReprovadas.setObjectName("lbNumPecasReprovadas")
        self.txaInformacoes = QtWidgets.QTextEdit(TelaExecucao)
        self.txaInformacoes.setGeometry(QtCore.QRect(170, 370, 711, 211))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.txaInformacoes.setFont(font)
        self.txaInformacoes.setObjectName("txaInformacoes")
        self.btVoltar = QtWidgets.QPushButton(TelaExecucao)
        self.btVoltar.setGeometry(QtCore.QRect(840, 670, 120, 60))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.btVoltar.setFont(font)
        self.btVoltar.setObjectName("btVoltar")

        self.retranslateUi(TelaExecucao)
        QtCore.QMetaObject.connectSlotsByName(TelaExecucao)

    def retranslateUi(self, TelaExecucao):
        _translate = QtCore.QCoreApplication.translate
        TelaExecucao.setWindowTitle(_translate("TelaExecucao", "Form"))
        self.lbNumPecasAprovadas.setText(_translate("TelaExecucao", "<html><head/><body><p align=\"center\">0</p></body></html>"))
        self.label_2.setText(_translate("TelaExecucao", "<html><head/><body><p align=\"center\">Peças aprovadas</p></body></html>"))
        self.label_3.setText(_translate("TelaExecucao", "<html><head/><body><p align=\"center\">Peças reprovadas</p></body></html>"))
        self.lbNumPecasReprovadas.setText(_translate("TelaExecucao", "<html><head/><body><p align=\"center\">0</p></body></html>"))
        self.txaInformacoes.setHtml(_translate("TelaExecucao", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'PibotoLt\'; font-size:24pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Informações:</p></body></html>"))
        self.btVoltar.setText(_translate("TelaExecucao", "VOLTAR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TelaExecucao = QtWidgets.QWidget()
    ui = Ui_TelaExecucao()
    ui.setupUi(TelaExecucao)
    TelaExecucao.show()
    sys.exit(app.exec_())
